workflow update for cd trial1

diff --git a/.github/workflows/build_ami.yml b/.github/workflows/build_ami.yml
--- a/.github/workflows/build_ami.yml
+++ b/.github/workflows/build_ami.yml
@@ -69,6 +69,39 @@ jobs:
           packer init ami.pkr.hcl
           packer build ami.pkr.hcl
           cd ..
-        
 
+      - name: Continue Deployment
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEMO_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEMO_SECRET_ACCESS_KEY }}
+        run: |
+          export MY_AMI_ID=$(aws ec2 describe-images \
+          --region us-west-2 \
+          --owners self \
+          --query "Images | sort_by(@, &CreationDate) | [-1].ImageId" \
+          --output text)
+          
+          LAUNCH_TEMPLATE_NAME="myLaunchTemplate"
+          
+      # Create new version of launch template with the latest AMI ID
+          NEW_TEMPLATE_VERSION=$(aws ec2 create-launch-template-version --launch-template-name $LAUNCH_TEMPLATE_NAME --source-version '$Latest' --launch-template-data '{"ImageId":"'$LATEST_AMI_ID'"}' --query 'LaunchTemplateVersion.VersionNumber' --output text)
+      
+      # [NEW] Update autoscaling group to use the latest version of the Launch Template
+          ASG_NAME="your-autoscaling-group-name"
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-template '{"LaunchTemplateName":"'$LAUNCH_TEMPLATE_NAME'", "Version":"'$NEW_TEMPLATE_VERSION'"}'
+      
+      # [NEW] Issue command to the auto-scale group to do an instance refresh
+          REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --strategy 'Rolling' --preferences '{"MinHealthyPercentage":50}' --query 'InstanceRefreshId' --output text)
+      
+      # [NEW] Wait for instance refresh to complete
+          STATUS="InProgress"
+          while [ "$STATUS" != "Successful" ]; do
+            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --instance-refresh-ids $REFRESH_ID --query 'InstanceRefreshes[0].Status' --output text)
+            echo "Refresh Status: $STATUS"
+            if [ "$STATUS" == "Failed" ]; then
+              echo "Instance refresh failed"
+              exit 1
+            fi
+            sleep 15
+          done
 
