Update build_ami.yml

diff --git a/.github/workflows/build_ami.yml b/.github/workflows/build_ami.yml
--- a/.github/workflows/build_ami.yml
+++ b/.github/workflows/build_ami.yml
@@ -88,20 +88,20 @@ jobs:
 
           NEW_TEMPLATE_VERSION=$(aws ec2 create-launch-template-version --launch-template-name $LAUNCH_TEMPLATE_NAME --source-version '$Latest' --launch-template-data '{"ImageId":"'$LATEST_AMI_ID'"}' --query 'LaunchTemplateVersion.VersionNumber' --output text --region us-west-2)
           
-          # ASG_NAME=myAutoScalingGroup
-          # aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-template '{"LaunchTemplateName":"'$LAUNCH_TEMPLATE_NAME'", "Version":"'$NEW_TEMPLATE_VERSION'"}'
+          ASG_NAME=myAutoScalingGroup
+          aws autoscaling update-auto-scaling-group --region us-west-2 --auto-scaling-group-name $ASG_NAME --launch-template '{"LaunchTemplateName":"'$LAUNCH_TEMPLATE_NAME'", "Version":"'$NEW_TEMPLATE_VERSION'"}'
           
-          # REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --strategy 'Rolling' --preferences '{"MinHealthyPercentage":50}' --query 'InstanceRefreshId' --output text)
+          REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --strategy 'Rolling' --preferences '{"MinHealthyPercentage":50}' --query 'InstanceRefreshId' --output text --region us-west-2)
           
-          # STATUS="InProgress"
-          # while [ "$STATUS" != "Successful" ]; do
-          #   STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --instance-refresh-ids $REFRESH_ID --query 'InstanceRefreshes[0].Status' --output text)
-          #   echo "Refresh Status: $STATUS"
-          #   if [ "$STATUS" == "Failed" ]; then
-          #     echo "Instance refresh failed"
-          #     exit 1
-          #   fi
-          #   sleep 15
-          # done
+          STATUS="InProgress"
+          while [ "$STATUS" != "Successful" ]; do
+            STATUS=$(aws autoscaling describe-instance-refreshes --region us-west-2 --auto-scaling-group-name $ASG_NAME --instance-refresh-ids $REFRESH_ID --query 'InstanceRefreshes[0].Status' --output text)
+            echo "Refresh Status: $STATUS"
+            if [ "$STATUS" == "Failed" ]; then
+              echo "Instance refresh failed"
+              exit 1
+            fi
+            sleep 15
+          done
 
 
